baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Danny Cunningham'
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 2  # Adjust the weight to change the order of items in the menu
