baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Danny Cunningham'

[params.author]
  name = "Danny Cunningham"

### enable LaTeX
# use `\( ... \)` for inline or `$$ ... $$` for block
# additional setup is in `layouts/partials/math.html` and `layout/partials/extend_head.html`

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"

[params]
  math = true
